### ISSUE TITLE
Add parameter to turn on and off advanced ACRE?

### ISSUE THREAD

**Issue by thealmightyn00b** [AttackingJoe/The-Company-Mission-Framework#11]
Should I add a parameter to turn on or off the advanced ACRE functionality. Currently by default it gives all factions separate Babel languages and radio frequencies. If factions want to talk to each other there has to be a translator, and for radios they either have to find an enemy one or have a scripted common frequency. I could separate this into two parameters, one for Babel and one for radio frequency. Thoughts?

**Comment by AttackingJoe** [comment]
Parameter may be overkill. Seems like something a mission maker should set.

**Comment by Smillmeister** [comment]
If agree with joe should be mission maker.

**Comment by thealmightyn00b** [comment]
So should I just put an option in the init.sqf. Just a bool variable that if true turns the stuff on, and if false turns it off?

**Comment by AttackingJoe** [comment]
Meaning you would define this option in the init.sqf while making the
mission instead of changing a parameter in the slotting screen?

**Comment by thealmightyn00b** [comment]
Yes

**Comment by thealmightyn00b** [comment]
Writing on in now.
