### ISSUE TITLE
Add map flash light to default TCMF gear scripts

### ISSUE THREAD

**Issue by AttackingJoe** [AttackingJoe/The-Company-Mission-Framework#23]

**Comment by Keybladebearer** [comment]
Red or white light?

**Comment by AttackingJoe** [comment]
White

**Comment by Keybladebearer** [comment]
This is finished, Added "ACE_Flashlight_XL50" to ACE Default and ACE Medic. in LoadoutsEUG, LoadoutsRUS, and LoadoutsUSA.

**Comment by AttackingJoe** [comment]
You pushed this to the master branch, I'm going to undo it, will you please
repush to the 5.2 beta branch

**Comment by Keybladebearer** [comment]
OH OOPS. Done, if you didn't roll back yet, go ahead on your earliest
