### ISSUE TITLE
Make independent faction template.

### ISSUE THREAD

**Issue by thealmightyn00b** [AttackingJoe/The-Company-Mission-Framework#3]
We lack a independent faction template on map in the editor although our marker script allows for it. We need to add an independent faction template so that there are native markers for all factions except civilian.

**Comment by thealmightyn00b** [comment]
We still need this to get done. Hope to get it done by 5.1 release

**Comment by AttackingJoe** [comment]
Will take care of tonight or tomorrow.

**Comment by Keybladebearer** [comment]
This is done and uploaded to the 5.1 branch as LoadoutsEUG
